# .instantiate/config.yml
orchestrator: compose
stackfile: docker-compose.yml

services:
  front:
    ports: 1
  backend:
    prebuild:
      image: node:23
      commands:
        - npm install
    repository:
      repo: https://github.com/valcriss/Instantiate-test-backend.git
      branch: main
      behavior: match
    ports: 1